-- AlterTable
ALTER TABLE "Customer" ADD COLUMN     "panNumber" TEXT,
ADD COLUMN     "registrationId" TEXT;

-- AlterTable
ALTER TABLE "Karigar" ALTER COLUMN "openingGold" SET DATA TYPE DECIMAL(12,5);

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "defaultGrossWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "defaultNetWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "defaultStoneWeight" SET DATA TYPE DECIMAL(12,5);

-- AlterTable
ALTER TABLE "InventoryStock" ALTER COLUMN "grossWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "lessWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "netWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "stoneWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "dmoWeight" SET DATA TYPE DECIMAL(12,5);

-- AlterTable
ALTER TABLE "InventoryTransaction" ALTER COLUMN "grossWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "netWeight" SET DATA TYPE DECIMAL(12,5);

-- AlterTable
ALTER TABLE "KachaInvoiceItem" ALTER COLUMN "grossWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "netWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "dmoWeight" SET DATA TYPE DECIMAL(12,5);

-- AlterTable
ALTER TABLE "InvoiceItem" ADD COLUMN     "cgstAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "hmCharge" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "hsnCode" TEXT,
ADD COLUMN     "schemeDiscount" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "sgstAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN     "stoneWeight" DECIMAL(12,5),
ALTER COLUMN "grossWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "netWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "dmoWeight" SET DATA TYPE DECIMAL(12,5);

-- AlterTable
ALTER TABLE "LedgerEntry" ALTER COLUMN "metalWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "metalWeightFine" SET DATA TYPE DECIMAL(12,5);

-- AlterTable
ALTER TABLE "KarigarJob" ALTER COLUMN "issueWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "issueFineWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "receiveWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "receiveFineWeight" SET DATA TYPE DECIMAL(12,5);

-- AlterTable
ALTER TABLE "PurchaseItem" ALTER COLUMN "grossWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "netWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "dmoWeight" SET DATA TYPE DECIMAL(12,5);

-- AlterTable
ALTER TABLE "KarigarReceiptItem" ALTER COLUMN "grossWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "netWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "stoneWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "dmoWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "fineWeight" SET DATA TYPE DECIMAL(12,5);

-- AlterTable
ALTER TABLE "QuotationItem" ALTER COLUMN "grossWeight" SET DATA TYPE DECIMAL(12,5),
ALTER COLUMN "netWeight" SET DATA TYPE DECIMAL(12,5);

-- AlterTable
ALTER TABLE "MetalRate" ADD COLUMN     "gold14k" DECIMAL(12,2),
ADD COLUMN     "platinum95" DECIMAL(12,2);

-- AlterTable
ALTER TABLE "BusinessSettings" ADD COLUMN     "cin" TEXT;

