export const INDIA_STATES_AND_CITIES = [
  {
    name: "Andhra Pradesh",
    code: "AP",
    cities: [
      "Visakhapatnam",
      "Vijayawada",
      "Guntur",
      "Nellore",
      "Kurnool",
      "Rajahmundry",
      "Tirupati",
      "Kadapa",
      "Anantapur",
      "Eluru",
      "Ongole",
      "Machilipatnam",
      "Adoni",
      "Tenali",
      "Chittoor",
      "Hindupur",
      "Proddatur",
      "Bhimavaram",
      "Madanapalle",
      "Gudivada",
    ],
  },
  {
    name: "Arunachal Pradesh",
    code: "AR",
    cities: [
      "Itanagar",
      "Naharlagun",
      "Pasighat",
      "Tawang",
      "Ziro",
      "Bomdila",
      "Aalo",
      "Tezu",
      "Roing",
      "Namsai",
    ],
  },
  {
    name: "Assam",
    code: "AS",
    cities: [
      "Guwahati",
      "Silchar",
      "Dibrugarh",
      "Jorhat",
      "Nagaon",
      "Tinsukia",
      "Tezpur",
      "Bongaigaon",
      "Dhubri",
      "Diphu",
      "Sivasagar",
      "Karimganj",
      "Golaghat",
      "Barpeta",
      "North Lakhimpur",
    ],
  },
  {
    name: "Bihar",
    code: "BR",
    cities: [
      "Patna",
      "Gaya",
      "Bhagalpur",
      "Muzaffarpur",
      "Darbhanga",
      "Purnia",
      "Arrah",
      "Begusarai",
      "Katihar",
      "Munger",
      "Chhapra",
      "Bihar Sharif",
      "Samastipur",
      "Sasaram",
      "Motihari",
    ],
  },
  {
    name: "Chhattisgarh",
    code: "CG",
    cities: [
      "Raipur",
      "Bhilai",
      "Bilaspur",
      "Korba",
      "Durg",
      "Rajnandgaon",
      "Jagdalpur",
      "Raigarh",
      "Ambikapur",
      "Mahasamund",
      "Dhamtari",
      "Janjgir",
    ],
  },
  {
    name: "Goa",
    code: "GA",
    cities: [
      "Panaji",
      "Margao",
      "Vasco da Gama",
      "Mapusa",
      "Ponda",
      "Bicholim",
      "Curchorem",
      "Sanquelim",
      "Canacona",
      "Valpoi",
    ],
  },
  {
    name: "Gujarat",
    code: "GJ",
    cities: [
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Bhavnagar",
      "Jamnagar",
      "Junagadh",
      "Gandhinagar",
      "Anand",
      "Navsari",
      "Morbi",
      "Nadiad",
      "Bharuch",
      "Mehsana",
      "Porbandar",
      "Palanpur",
      "Valsad",
      "Vapi",
      "Godhra",
      "Amreli",
    ],
  },
  {
    name: "Haryana",
    code: "HR",
    cities: [
      "Faridabad",
      "Gurugram",
      "Panipat",
      "Ambala",
      "Yamunanagar",
      "Rohtak",
      "Hisar",
      "Karnal",
      "Sonipat",
      "Panchkula",
      "Bhiwani",
      "Sirsa",
      "Bahadurgarh",
      "Jind",
      "Thanesar",
      "Kaithal",
    ],
  },
  {
    name: "Himachal Pradesh",
    code: "HP",
    cities: [
      "Shimla",
      "Dharamshala",
      "Solan",
      "Mandi",
      "Baddi",
      "Nahan",
      "Bilaspur",
      "Hamirpur",
      "Kullu",
      "Chamba",
      "Una",
      "Palampur",
      "Sundarnagar",
    ],
  },
  {
    name: "Jharkhand",
    code: "JH",
    cities: [
      "Ranchi",
      "Jamshedpur",
      "Dhanbad",
      "Bokaro",
      "Deoghar",
      "Hazaribagh",
      "Giridih",
      "Ramgarh",
      "Medininagar",
      "Phusro",
      "Chirkunda",
      "Chaibasa",
    ],
  },
  {
    name: "Karnataka",
    code: "KA",
    cities: [
      "Bengaluru",
      "Mysuru",
      "Hubballi",
      "Mangaluru",
      "Belagavi",
      "Kalaburagi",
      "Davanagere",
      "Ballari",
      "Shivamogga",
      "Tumakuru",
      "Raichur",
      "Bidar",
      "Hospet",
      "Hassan",
      "Udupi",
      "Chikkamagaluru",
      "Mandya",
      "Kolar",
      "Vijayapura",
      "Bagalkot",
    ],
  },
  {
    name: "Kerala",
    code: "KL",
    cities: [
      "Thiruvananthapuram",
      "Kochi",
      "Kozhikode",
      "Thrissur",
      "Kollam",
      "Alappuzha",
      "Kannur",
      "Palakkad",
      "Kottayam",
      "Malappuram",
      "Kasaragod",
      "Pathanamthitta",
      "Idukki",
      "Wayanad",
      "Ponnani",
      "Vatakara",
    ],
  },
  {
    name: "Madhya Pradesh",
    code: "MP",
    cities: [
      "Indore",
      "Bhopal",
      "Jabalpur",
      "Gwalior",
      "Ujjain",
      "Sagar",
      "Dewas",
      "Satna",
      "Ratlam",
      "Rewa",
      "Murwara",
      "Singrauli",
      "Burhanpur",
      "Khandwa",
      "Vidisha",
      "Chhindwara",
      "Shivpuri",
      "Mandsaur",
      "Bhind",
      "Sehore",
    ],
  },
  {
    name: "Maharashtra",
    code: "MH",
    cities: [
      "Mumbai",
      "Pune",
      "Nagpur",
      "Nashik",
      "Thane",
      "Navi Mumbai",
      "Aurangabad",
      "Solapur",
      "Amravati",
      "Kolhapur",
      "Nanded",
      "Sangli",
      "Jalgaon",
      "Akola",
      "Latur",
      "Dhule",
      "Ahmednagar",
      "Chandrapur",
      "Parbhani",
      "Yavatmal",
      "Satara",
      "Beed",
      "Panvel",
      "Ratnagiri",
      "Wardha",
    ],
  },
  {
    name: "Manipur",
    code: "MN",
    cities: [
      "Imphal",
      "Thoubal",
      "Bishnupur",
      "Churachandpur",
      "Ukhrul",
      "Senapati",
      "Kakching",
      "Tamenglong",
      "Jiribam",
    ],
  },
  {
    name: "Meghalaya",
    code: "ML",
    cities: [
      "Shillong",
      "Tura",
      "Jowai",
      "Nongpoh",
      "Baghmara",
      "Williamnagar",
      "Resubelpara",
      "Mairang",
    ],
  },
  {
    name: "Mizoram",
    code: "MZ",
    cities: [
      "Aizawl",
      "Lunglei",
      "Champhai",
      "Saiha",
      "Kolasib",
      "Serchhip",
      "Lawngtlai",
      "Mamit",
    ],
  },
  {
    name: "Nagaland",
    code: "NL",
    cities: [
      "Kohima",
      "Dimapur",
      "Mokokchung",
      "Tuensang",
      "Wokha",
      "Mon",
      "Zunheboto",
      "Phek",
      "Kiphire",
    ],
  },
  {
    name: "Odisha",
    code: "OD",
    cities: [
      "Bhubaneswar",
      "Cuttack",
      "Rourkela",
      "Sambalpur",
      "Berhampur",
      "Puri",
      "Balasore",
      "Bhadrak",
      "Baripada",
      "Jharsuguda",
      "Jeypore",
      "Rayagada",
      "Angul",
      "Dhenkanal",
      "Koraput",
    ],
  },
  {
    name: "Punjab",
    code: "PB",
    cities: [
      "Ludhiana",
      "Amritsar",
      "Jalandhar",
      "Patiala",
      "Bathinda",
      "Mohali",
      "Hoshiarpur",
      "Batala",
      "Pathankot",
      "Moga",
      "Abohar",
      "Malerkotla",
      "Khanna",
      "Phagwara",
      "Muktsar",
    ],
  },
  {
    name: "Rajasthan",
    code: "RJ",
    cities: [
      "Jaipur",
      "Jodhpur",
      "Udaipur",
      "Kota",
      "Bikaner",
      "Ajmer",
      "Bhilwara",
      "Alwar",
      "Bharatpur",
      "Sikar",
      "Pali",
      "Sri Ganganagar",
      "Kishangarh",
      "Barmer",
      "Tonk",
      "Beawar",
      "Hanumangarh",
      "Churu",
      "Jhunjhunu",
      "Nagaur",
    ],
  },
  {
    name: "Sikkim",
    code: "SK",
    cities: [
      "Gangtok",
      "Namchi",
      "Gyalshing",
      "Mangan",
      "Singtam",
      "Rangpo",
      "Jorethang",
    ],
  },
  {
    name: "Tamil Nadu",
    code: "TN",
    cities: [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Tiruchirappalli",
      "Salem",
      "Tirunelveli",
      "Erode",
      "Vellore",
      "Thoothukudi",
      "Dindigul",
      "Thanjavur",
      "Ranipet",
      "Sivakasi",
      "Karur",
      "Hosur",
      "Nagercoil",
      "Kanchipuram",
      "Cuddalore",
      "Kumbakonam",
      "Pollachi",
      "Tiruppur",
      "Avadi",
    ],
  },
  {
    name: "Telangana",
    code: "TS",
    cities: [
      "Hyderabad",
      "Warangal",
      "Nizamabad",
      "Karimnagar",
      "Khammam",
      "Ramagundam",
      "Mahbubnagar",
      "Nalgonda",
      "Adilabad",
      "Suryapet",
      "Miryalaguda",
      "Siddipet",
      "Jagtial",
      "Kamareddy",
    ],
  },
  {
    name: "Tripura",
    code: "TR",
    cities: [
      "Agartala",
      "Udaipur",
      "Dharmanagar",
      "Kailashahar",
      "Belonia",
      "Khowai",
      "Ambassa",
      "Sabroom",
    ],
  },
  {
    name: "Uttar Pradesh",
    code: "UP",
    cities: [
      "Lucknow",
      "Kanpur",
      "Ghaziabad",
      "Agra",
      "Varanasi",
      "Meerut",
      "Prayagraj",
      "Noida",
      "Aligarh",
      "Moradabad",
      "Saharanpur",
      "Gorakhpur",
      "Bareilly",
      "Jhansi",
      "Muzaffarnagar",
      "Mathura",
      "Ayodhya",
      "Firozabad",
      "Shahjahanpur",
      "Rampur",
      "Etawah",
      "Fatehpur",
      "Basti",
      "Sitapur",
      "Unnao",
    ],
  },
  {
    name: "Uttarakhand",
    code: "UK",
    cities: [
      "Dehradun",
      "Haridwar",
      "Roorkee",
      "Haldwani",
      "Rudrapur",
      "Kashipur",
      "Rishikesh",
      "Kotdwar",
      "Pithoragarh",
      "Almora",
      "Nainital",
      "Champawat",
    ],
  },
  {
    name: "West Bengal",
    code: "WB",
    cities: [
      "Kolkata",
      "Howrah",
      "Durgapur",
      "Asansol",
      "Siliguri",
      "Malda",
      "Bardhaman",
      "Kharagpur",
      "Haldia",
      "Raiganj",
      "Krishnanagar",
      "Berhampore",
      "Jalpaiguri",
      "Balurghat",
      "Darjeeling",
    ],
  },

  // Union Territories
  {
    name: "Andaman and Nicobar Islands",
    code: "AN",
    cities: [
      "Port Blair",
      "Diglipur",
      "Mayabunder",
      "Rangat",
      "Hut Bay",
      "Car Nicobar",
    ],
  },
  {
    name: "Chandigarh",
    code: "CH",
    cities: ["Chandigarh"],
  },
  {
    name: "Dadra and Nagar Haveli and Daman and Diu",
    code: "DN",
    cities: [
      "Daman",
      "Diu",
      "Silvassa",
      "Dadra",
      "Naroli",
      "Amli",
    ],
  },
  {
    name: "Delhi",
    code: "DL",
    cities: [
      "New Delhi",
      "Delhi",
      "Dwarka",
      "Rohini",
      "Karol Bagh",
      "Saket",
      "Janakpuri",
      "Pitampura",
      "Shahdara",
    ],
  },
  {
    name: "Jammu and Kashmir",
    code: "JK",
    cities: [
      "Srinagar",
      "Jammu",
      "Anantnag",
      "Baramulla",
      "Udhampur",
      "Kathua",
      "Kupwara",
      "Pulwama",
      "Sopore",
    ],
  },
  {
    name: "Ladakh",
    code: "LA",
    cities: [
      "Leh",
      "Kargil",
      "Diskit",
      "Nubra",
    ],
  },
  {
    name: "Lakshadweep",
    code: "LD",
    cities: [
      "Kavaratti",
      "Agatti",
      "Amini",
      "Andrott",
      "Kalpeni",
      "Minicoy",
    ],
  },
  {
    name: "Puducherry",
    code: "PY",
    cities: [
      "Puducherry",
      "Karaikal",
      "Mahe",
      "Yanam",
    ],
  },
] as const