// File: src/lib/roles.ts

import { UserRole } from "@prisma/client";
import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  ADMIN: Object.values(PERMISSIONS),

  MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,

    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,

    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,

    PERMISSIONS.SUPPLIER_VIEW,
    PERMISSIONS.SUPPLIER_CREATE,
    PERMISSIONS.SUPPLIER_UPDATE,

    PERMISSIONS.REPORT_VIEW,
  ],

  STAFF: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.CUSTOMER_VIEW,

    PERMISSIONS.PRODUCT_VIEW,

    PERMISSIONS.INVENTORY_VIEW,
  ],
};