-- CreateEnum
CREATE TYPE "SkuFormat" AS ENUM ('METAL_PURITY_STYLE_CATEGORY', 'METAL_CATEGORY_PURITY', 'CATEGORY_METAL_PURITY', 'STYLE_CATEGORY_METAL_PURITY');

-- AlterTable
ALTER TABLE "BusinessSettings" ADD COLUMN     "skuFormat" "SkuFormat" NOT NULL DEFAULT 'METAL_PURITY_STYLE_CATEGORY';
